services:
  - type: web
    name: portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portal.wsgi
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.8
