# Generated by Django 4.2.30 on 2026-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_id', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=30)),
                ('l_email', models.EmailField(max_length=254)),
                ('l_subject', models.CharField(max_length=30)),
            ],
        ),
    ]
