# Generated by Django 4.2.30 on 2026-04-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sdetails',
            name='roll_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
